CREATE TABLE IF NOT EXISTS log (
  id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL,
  flag TEXT, nick TEXT NOT NULL, userhost TEXT, handle TEXT,
  message TEXT NOT NULL
);

CREATE VIRTUAL TABLE IF NOT EXISTS log_fts USING fts5 (
  id UNINDEXED, nick UNINDEXED, message, content=log, content_rowid=id
);

CREATE TABLE IF NOT EXISTS nicknames (
  nick TEXT NOT NULL PRIMARY KEY COLLATE NOCASE
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS idx_log_nick ON log(nick);
CREATE INDEX IF NOT EXISTS idx_log_date ON log(date);

CREATE TRIGGER IF NOT EXISTS log_bu BEFORE UPDATE ON log BEGIN
  DELETE FROM log_fts WHERE rowid=old.id;
END;
CREATE TRIGGER IF NOT EXISTS log_bd BEFORE DELETE ON log BEGIN
  DELETE FROM log_fts WHERE rowid=old.id;
END;
CREATE TRIGGER IF NOT EXISTS log_au AFTER UPDATE ON log BEGIN
  INSERT INTO log_fts (rowid, message) VALUES (new.id, new.message);
END;
CREATE TRIGGER IF NOT EXISTS log_ai AFTER INSERT ON log BEGIN
  INSERT INTO log_fts (rowid, message) VALUES (new.id, new.message);
END;
CREATE TRIGGER IF NOT EXISTS log_bi BEFORE INSERT ON log BEGIN
  INSERT OR IGNORE INTO nicknames (nick) VALUES (new.nick);
END;
